# Generated by Django 5.2.6 on 2025-09-25 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('total_miles', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('off_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sleeper_berth_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('on_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'ordering': ['trip', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=20)),
                ('start_hour', models.DecimalField(decimal_places=2, max_digits=4)),
                ('end_hour', models.DecimalField(decimal_places=2, max_digits=4)),
                ('location', models.CharField(max_length=100)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.dailylog')),
            ],
            options={
                'ordering': ['daily_log', 'start_hour'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Hours already used in current 8-day cycle (max 70)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_stops', models.IntegerField(default=0)),
                ('required_rest_stops', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='core.trip'),
        ),
        migrations.CreateModel(
            name='TripSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('driving', 'Driving'), ('rest_break', '30-min Rest Break'), ('sleeper_berth', 'Sleeper Berth'), ('fuel', 'Fueling'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('sequence_number', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('location', models.CharField(max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('trip', 'day_number')},
        ),
    ]
